#!/bin/bash

dir=/var/lib/rkt/pods/run
uuid=${@: -1}
pod=$dir/$uuid
stage1=$pod/stage1/rootfs
# Assumes 1 App
stage2m=$pod/pod
gargs=""
ip=""
gw=""
route=""
pvcalls=0
bridge="xenbr0"

for i in $*
do
    if [ $i = "--interactive" ]
    then
        gargs="-c"
    fi
	if [ $i = "pvcalls" ]
	then
		pvcalls=1
	fi
	if [[ $i = "ip="* ]]
	then
		ip=${i#ip=}
	fi
	if [[ $i = "gw="* ]]
	then
		gw=${i#gw=}
	fi
	if [[ $i = "route="* ]]
	then
		route=${i#route=}
	fi
	if [[ $i = "bridge="* ]]
	then
		bridge=${i#bridge=}
	fi
done

appname=`cat $stage2m | jq -r '.["apps"][0]["name"]'`
cmdline=`cat $stage2m | jq  -c -r '.["apps"][0]["app"]["exec"] | join("\" \"")'`
cmdline="\"$cmdline\""
stage2=$stage1/opt/stage2/$appname

workpath=$stage1
mkdir -p $workpath/out
vmconfig=$workpath/vmconfig
outconfig=$workpath/out/test.0
mountpoint=$stage2

rm $outconfig &> /dev/null
echo "kernel='$workpath/kernel'" >> $outconfig
echo "ramdisk='$workpath/initrd'" >> $outconfig
echo "p9=[ 'tag=share_dir,security_model=none,path=$mountpoint' ]" >> $outconfig

if [ -f "$STAGE1_SEED_XL_CFG" ] ; then
    grep -Ev '^(disk|bootloader|root|extra|kernel)' < "$STAGE1_SEED_XL_CFG" >> $outconfig
    echo extra=\'console=hvc0 root=9p\' >> $outconfig
else	
    echo "memory = 1024" >> $outconfig
    echo "vcpus = 2" >> $outconfig
    echo "serial='pty'" >> $outconfig
    echo "boot='c'" >> $outconfig
    echo "vfb=['vnc=1']" >> $outconfig
    echo "name=\"$uuid\"" >> $outconfig
    if test $pvcalls -eq 0
    then
    	if test $bridge = "vif"
    	then
    		echo "vif=['script=vif-nat,ip=$ip']" >> $outconfig
    	else
    		echo "vif=['bridge=$bridge']" >> $outconfig
    	fi
    	echo extra=\'console=hvc0 root=9p ip=$ip gw=$gw route=$route\' >> $outconfig 
    else
    	echo "pvcalls=['']" >> $outconfig
    	echo extra=\'console=hvc0 root=9p pvcalls=1\' >> $outconfig 
    fi
fi    

echo $cmdline > $mountpoint/cmdline
export IFS=$'\n'
stage2manifest=$mountpoint/manifest
stage2env=$mountpoint/environment
for row in `cat $stage2manifest | jq -c .app.environment[]`; do
  KEY=$(echo $row | jq -r .name)
  VALUE=$(echo $row | jq -r .value)
  echo export $KEY=\'$VALUE\' >> $stage2env
done

xl create $gargs $outconfig $STAGE1_XL_OPTS
domname=$(sed -ne '/^name *=/s/^.*"\(.*\)"/\1/p' < "$outconfig")
domid=`xl list | grep "$domname" | awk '{print$2}'`
echo $domid > $pod/pid
